package cm;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Christoph Percival
 */

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private static final Color DEFAULT_TEXT_COLOR = Color.WHITE;
    private static final Color HOVER_TEXT_COLOR = Color.RED;
    private static final Color MIN_HOVER_TEXT_COLOR = Color.GREEN;
    
    public Login() {
        initComponents();
        //Center Form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHeader = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblTextHeader = new javax.swing.JLabel();
        panBody = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        chkShowHide = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        lblForgot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmLogin"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        panHeader.setBackground(new java.awt.Color(46, 204, 113));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setText("X");
        lblClose.setToolTipText("Exit");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblTextHeader.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTextHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTextHeader.setText("Login");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblTextHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTextHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panBody.setBackground(new java.awt.Color(44, 62, 80));
        panBody.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panBody.setLayout(null);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(236, 240, 241));
        lblPassword.setText("Password:");
        panBody.add(lblPassword);
        lblPassword.setBounds(30, 110, 100, 30);

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(236, 240, 241));
        lblUsername.setText("Username:");
        panBody.add(lblUsername);
        lblUsername.setBounds(30, 50, 100, 30);

        txtUsername.setBackground(new java.awt.Color(108, 122, 137));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtUsername);
        txtUsername.setBounds(120, 50, 220, 30);

        txtPassword.setBackground(new java.awt.Color(108, 122, 137));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtPassword);
        txtPassword.setBounds(120, 110, 220, 30);

        chkShowHide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkShowHide.setForeground(new java.awt.Color(255, 255, 255));
        chkShowHide.setText("Show");
        chkShowHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkShowHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowHideActionPerformed(evt);
            }
        });
        panBody.add(chkShowHide);
        chkShowHide.setBounds(350, 110, 69, 31);

        btnLogin.setBackground(new java.awt.Color(30, 139, 195));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setMnemonic('L');
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panBody.add(btnLogin);
        btnLogin.setBounds(240, 180, 100, 35);

        btnCancel.setBackground(new java.awt.Color(242, 38, 19));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panBody.add(btnCancel);
        btnCancel.setBounds(120, 180, 100, 35);

        lblCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblCreate.setText("Create Account");
        lblCreate.setToolTipText("Create a New Account");
        lblCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateMouseClicked(evt);
            }
        });
        panBody.add(lblCreate);
        lblCreate.setBounds(180, 230, 130, 22);

        lblForgot.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblForgot.setForeground(new java.awt.Color(255, 255, 255));
        lblForgot.setText("Forgot Password");
        lblForgot.setToolTipText("Forgotten Password");
        lblForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotMouseClicked(evt);
            }
        });
        panBody.add(lblForgot);
        lblForgot.setBounds(222, 145, 130, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBody, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panBody, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // Minimize Form
        this.setState((JFrame.ICONIFIED));
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Close App
        switch(JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            case JOptionPane.YES_OPTION:
                System.exit(0);
            case JOptionPane.NO_OPTION:
                return;
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void chkShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowHideActionPerformed
        // Show or Hide Password
        if (chkShowHide.isSelected()){
            chkShowHide.setText("Hide");
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            chkShowHide.setText("Show");
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowHideActionPerformed

    private void lblCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMouseClicked
        // Open Signup Form
        Signup signup = new Signup();
        signup.setVisible(true);
        signup.pack();
        signup.setLocationRelativeTo(null);
        signup.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lblCreateMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // Change ForeColor
        this.setForeground(HOVER_TEXT_COLOR);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // set ForeColor To Default
        this.setForeground(DEFAULT_TEXT_COLOR);
    }//GEN-LAST:event_lblCloseMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Close App
        switch(JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Cancel?", "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            case JOptionPane.YES_OPTION:
                System.exit(0);
            case JOptionPane.NO_OPTION:
                return;
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //If Fields Are Empty
        if (txtUsername.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Input Username", "Login", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocusInWindow();
            txtUsername.setText("");
            return;
        }
        
        if ((new String(txtPassword.getPassword())).trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Input Password", "Login", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocusInWindow();
            txtPassword.setText("");
            return;
        }

        // Login Details Verification
        if (!userFound())
        {
            return;
        }
        
        // Open Contatcs Form
        Contacts contacts;
        try {
            contacts = new Contacts(txtUsername.getText());
            contacts.setVisible(true);
            contacts.pack();
            contacts.setLocationRelativeTo(null);
            contacts.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseClicked
        //Display Reset Password Form
        ResetPassword resetPassword = new ResetPassword(new javax.swing.JFrame(), true);
        resetPassword.pack();
        resetPassword.setLocationRelativeTo(null);
        resetPassword.setVisible(true);
    }//GEN-LAST:event_lblForgotMouseClicked

    
    private boolean userFound()
    {
        try
        {
            Connection con = Database.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            
            ps = con.prepareStatement("SELECT Username, Password FROM persons WHERE Username LIKE ? AND Password LIKE ?");
            ps.setString(1, txtUsername.getText());
            ps.setString(2, new String(txtPassword.getPassword()));
            
            rs = ps.executeQuery();
            
            if (rs.next())
            {
                if (txtUsername.getText().equals(rs.getString(1)) && (new String(txtPassword.getPassword()).equals(rs.getString(2))))
                {
                    JOptionPane.showMessageDialog(null, "Login Successfully", "Login", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect Username / Password", "Login", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Username / Password", "Login", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Searching User", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
            return false;
        }
            
        return true;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowHide;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTextHeader;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panBody;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
