package cm;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.awt.Frame;

/**
 *
 * @author Christoph Percival
 */
public class Profile extends javax.swing.JDialog {

    /**
     * Creates new form Profile
     * @param parent
     * @param modal
     */
    
    private String path = null;
    
    public Profile(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Center Form
        this.setLocationRelativeTo(null);
        getUserDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHeader = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblTextHeader = new javax.swing.JLabel();
        panBody = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnUpdateDetails = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblVerifyPassword = new javax.swing.JLabel();
        txtVerifyPassword = new javax.swing.JPasswordField();
        lblPicture = new javax.swing.JLabel();
        lblPictureShow = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        chkShowHide = new javax.swing.JCheckBox();
        lblPassword1 = new javax.swing.JLabel();
        jSeparatorHorizontal = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(505, 540));
        setSize(new java.awt.Dimension(0, 0));

        panHeader.setBackground(new java.awt.Color(46, 204, 113));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setText("X");
        lblClose.setToolTipText("Exit");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblTextHeader.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTextHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTextHeader.setText("Profile");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblTextHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTextHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panBody.setBackground(new java.awt.Color(44, 62, 80));
        panBody.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panBody.setLayout(null);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(236, 240, 241));
        lblPassword.setText("New Password:");
        panBody.add(lblPassword);
        lblPassword.setBounds(10, 350, 130, 30);

        txtPassword.setBackground(new java.awt.Color(108, 122, 137));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtPassword);
        txtPassword.setBounds(150, 350, 236, 30);

        btnUpdateDetails.setBackground(new java.awt.Color(30, 139, 195));
        btnUpdateDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateDetails.setMnemonic('U');
        btnUpdateDetails.setText("Update Details");
        btnUpdateDetails.setToolTipText("Update Your Details");
        btnUpdateDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDetailsActionPerformed(evt);
            }
        });
        panBody.add(btnUpdateDetails);
        btnUpdateDetails.setBounds(40, 250, 390, 35);

        btnChangePassword.setBackground(new java.awt.Color(242, 38, 19));
        btnChangePassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setMnemonic('C');
        btnChangePassword.setText("Change Password");
        btnChangePassword.setToolTipText("Change Password");
        btnChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        panBody.add(btnChangePassword);
        btnChangePassword.setBounds(40, 430, 390, 35);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(236, 240, 241));
        lblFirstName.setText("First Name:");
        panBody.add(lblFirstName);
        lblFirstName.setBounds(10, 10, 100, 30);

        txtFirstName.setBackground(new java.awt.Color(108, 122, 137));
        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtFirstName);
        txtFirstName.setBounds(150, 10, 240, 30);

        txtLastName.setBackground(new java.awt.Color(108, 122, 137));
        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtLastName);
        txtLastName.setBounds(150, 50, 240, 30);

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(236, 240, 241));
        lblLastName.setText("Last Name:");
        panBody.add(lblLastName);
        lblLastName.setBounds(10, 50, 100, 30);

        lblVerifyPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVerifyPassword.setForeground(new java.awt.Color(236, 240, 241));
        lblVerifyPassword.setText("Verify Password:");
        panBody.add(lblVerifyPassword);
        lblVerifyPassword.setBounds(10, 390, 140, 30);

        txtVerifyPassword.setBackground(new java.awt.Color(108, 122, 137));
        txtVerifyPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVerifyPassword.setForeground(new java.awt.Color(253, 227, 167));
        panBody.add(txtVerifyPassword);
        txtVerifyPassword.setBounds(150, 390, 236, 30);

        lblPicture.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPicture.setForeground(new java.awt.Color(236, 240, 241));
        lblPicture.setText("Picture:");
        panBody.add(lblPicture);
        lblPicture.setBounds(40, 80, 70, 30);

        lblPictureShow.setBackground(new java.awt.Color(108, 122, 137));
        lblPictureShow.setOpaque(true);
        panBody.add(lblPictureShow);
        lblPictureShow.setBounds(150, 90, 160, 140);

        btnLoad.setBackground(new java.awt.Color(255, 255, 255));
        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoad.setMnemonic('L');
        btnLoad.setText("Load");
        btnLoad.setToolTipText("Load Image");
        btnLoad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        panBody.add(btnLoad);
        btnLoad.setBounds(320, 90, 70, 25);

        chkShowHide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkShowHide.setForeground(new java.awt.Color(255, 255, 255));
        chkShowHide.setText("Show");
        chkShowHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkShowHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowHideActionPerformed(evt);
            }
        });
        panBody.add(chkShowHide);
        chkShowHide.setBounds(392, 370, 69, 31);

        lblPassword1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(236, 240, 241));
        lblPassword1.setText("Password Change");
        panBody.add(lblPassword1);
        lblPassword1.setBounds(130, 300, 230, 30);
        panBody.add(jSeparatorHorizontal);
        jSeparatorHorizontal.setBounds(20, 293, 430, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panBody, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // Close App
        switch(JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            case JOptionPane.YES_OPTION -> this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDetailsActionPerformed

        //DO VALIDATIONS
        //                  First Name Validation
        if (!Details.nameIsValid(txtFirstName, "First Name"))
        {
            return;
        }

        //                  Last Name Validation
        if (!Details.nameIsValid(txtLastName, "Last Name"))
        {
            return;
        }

        //Validation Complete. Now Send Data To Database
        switch(JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Update Your Details?", "Update Details", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            case JOptionPane.YES_OPTION -> {
                try
                {
                    Connection con = Database.getConnection();
                    PreparedStatement ps;
                    //ps = con.prepareStatement("Insert Into 'persons' ('FirstName', 'LastName', 'Username', 'Password', 'Picture') Values (?, ?, ?, ?, ?)");
                    if (path == null)
                    {
                        ps = con.prepareStatement("Update persons Set FirstName = ?, LastName = ? WHERE id LIKE ?");
                        ps.setString(1, txtFirstName.getText());
                        ps.setString(2, txtLastName.getText());
                        ps.setInt(3, Contacts.userId);
                    }
                    else
                    {
                        ps = con.prepareStatement("Update persons Set FirstName = ?, LastName = ?, Picture = ? WHERE id LIKE ?");
                        ps.setString(1, txtFirstName.getText());
                        ps.setString(2, txtLastName.getText());
                        InputStream img = new FileInputStream(new File(path));
                        ps.setBlob(3, img);
                        ps.setInt(4, Contacts.userId);
                    }
                    
                    //Returns number of Rows Affected, 0 if none
                    if (ps.executeUpdate() != 0)
                    {
                        JOptionPane.showMessageDialog(null, "Your Details Updated Successfully", "Update Details", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error While Updating Your Details", "Update Details", JOptionPane.ERROR_MESSAGE);
                    }

                    btnLoad.requestFocusInWindow();
                    Contacts.contacts.refreshProfile();

                }
                catch (FileNotFoundException | SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Update Details", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnUpdateDetailsActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        //DO VALIDATIONS
        //                  Password Validation
        if (!passwordIsValid())
        {
            return;
        }

        //Validation Complete. Now Send Data To Database
        switch(JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Change Your Password?", "Password Change", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            case JOptionPane.YES_OPTION -> {
                try
                {
                    Connection con = Database.getConnection();
                    PreparedStatement ps;
                    //ps = con.prepareStatement("Insert Into 'persons' ('FirstName', 'LastName', 'Username', 'Password', 'Picture') Values (?, ?, ?, ?, ?)");
                    ps = con.prepareStatement("Update persons Set Password = ? WHERE id LIKE ?");
                    ps.setString(1, new String(txtPassword.getPassword()));
                    ps.setInt(2, Contacts.userId);

                    //Returns number of Rows Affected, 0 if none
                    if (ps.executeUpdate() != 0)
                    {
                        JOptionPane.showMessageDialog(null, "Your Password Changed Successfully", "Password Change", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error While Changing Your Password", "Password Change", JOptionPane.ERROR_MESSAGE);
                    }

                    txtPassword.setText("");
                    txtVerifyPassword.setText("");
                    btnLoad.requestFocusInWindow();

                }
                catch (SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Password Change", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        Image image = new Image();
        path = image.browse(lblPictureShow);
    }//GEN-LAST:event_btnLoadActionPerformed

    private void chkShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowHideActionPerformed
        // Show or Hide Password
        if (chkShowHide.isSelected()){
            chkShowHide.setText("Hide");
            txtPassword.setEchoChar((char)0);
            txtVerifyPassword.setEchoChar((char)0);
        }
        else
        {
            chkShowHide.setText("Show");
            txtPassword.setEchoChar('*');
            txtVerifyPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowHideActionPerformed

    
    //Get User Details
    private void getUserDetails()
    {
        try
        {
            Connection con = Database.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            
            ps = con.prepareStatement("SELECT FirstName, LastName, Picture FROM persons WHERE id LIKE ?");
            ps.setInt(1, Contacts.userId);
            
            rs = ps.executeQuery();
            
            if (rs.next())
            {
                txtFirstName.setText(rs.getString(1));
                txtLastName.setText(rs.getString(2));
                
                BufferedImage img = ImageIO.read(rs.getBinaryStream("Picture"));
                Image image = new Image();
                lblPictureShow.setIcon(image.resizeImage(img, lblPictureShow.getWidth(), lblPictureShow.getHeight()));
            }
        }
        catch(IOException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Searching User Details", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
            //return;
        }
    }
    
    //VALIDATIONS
    //                                  Password Validation
    private boolean passwordIsValid()
    {
        String password = new String(txtPassword.getPassword());
        String verPassword = new String(txtVerifyPassword.getPassword());
        
        if (!password.equals(""))
        {
            if (!password.contains(" "))
            {
                if (password.length() < 8)
                {
                    JOptionPane.showMessageDialog(null, "Password Must Have Minimum of 8 Characters", "New Password", JOptionPane.ERROR_MESSAGE);
                    txtPassword.requestFocusInWindow();
                    return false;
                }
                
                if (password.length() > 25)
                {
                    JOptionPane.showMessageDialog(null, "Password Can Only Have Maximum of 25 Characters", "New Password", JOptionPane.ERROR_MESSAGE);
                    txtPassword.requestFocusInWindow();
                    return false;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Password Cannot Contain Space Character", "New Password", JOptionPane.ERROR_MESSAGE);
                txtPassword.requestFocusInWindow();
                return false;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Input New Password", "New Password", JOptionPane.QUESTION_MESSAGE);
            txtPassword.requestFocusInWindow();
            return false;
        }
        
        if (verPassword.equals(("")))
        {
            JOptionPane.showMessageDialog(null, "Verify New Password", "New Password", JOptionPane.ERROR_MESSAGE);
            txtVerifyPassword.requestFocusInWindow();
            return false;
        }
        
        //Check If Password Match
        if (!password.equals(verPassword))
        {
            JOptionPane.showMessageDialog(null, "Passwords Do Not Match", "New Password", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocusInWindow();
            return false;
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Profile dialog = new Profile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnUpdateDetails;
    private javax.swing.JCheckBox chkShowHide;
    private javax.swing.JSeparator jSeparatorHorizontal;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPictureShow;
    private javax.swing.JLabel lblTextHeader;
    private javax.swing.JLabel lblVerifyPassword;
    private javax.swing.JPanel panBody;
    private javax.swing.JPanel panHeader;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtVerifyPassword;
    // End of variables declaration//GEN-END:variables
}
